on:
  push:
    branches:
      - main
  pull_request:

name: main

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
      - run: echo "::add-matcher::.github/sarif-matcher.json"
      - run: |
          curl -sSL https://github.com/psastras/sarif-rs/releases/download/latest-x86_64-unknown-linux-gnu/sarif-fmt -o sarif-fmt
          curl -sSL https://github.com/psastras/sarif-rs/releases/download/latest-x86_64-unknown-linux-gnu/hadolint-sarif -o hadolint-sarif
          chmod +x ./sarif-fmt ./hadolint-sarif
          nix-shell --run 'hadolint -f json Dockerfile | ./hadolint-sarif | ./sarif-fmt -f plain' nix/hadolint.nix
